name: Deploy Static Site to S3 with CDK

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Specify the Node.js version you are using

    - name: Install dependencies
      run: |
        npm install  # Install dependencies in the current directory

    - name: Run tests
      run: |
        npm test || exit 1   # Run the test script defined in package.json

    - name: Build Static Site
      run: |
        npm run build 

    - name: Install infra dependencies
      run: |
        cd infra  # Navigate to your CDK project directory
        npm install  # Install dependencies in the infra directory
  
    - name: Run infrastructure tests
      run: |
        cd infra  # Navigate to your CDK project directory
        npm run test || exit 1  # Run the test script defined in package.json

    - name: Deploy CDK Infrastructure
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ap-south-1  # Change to your desired region
      run: |
        cd infra  # Navigate to your CDK project directory
        npx cdk deploy --require-approval never